services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    command: npx nodemon index.js  # Use nodemon for auto-reloading in development
    restart: always
    env_file:
      - ./backend/.env
    networks:
      - Voxia

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - Voxia

networks:
    Voxia:
      driver: bridge
