name: Build and Push Docker Images

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file from secrets
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > ./backend/.env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> ./backend/.env
          echo "MONGODB_ATLAS_URI=${{ secrets.MONGODB_ATLAS_URI }}" >> ./.env
          echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" >> ./.env

      - name: Build Docker images
        run: |
          docker build -t dehkai/voxia-backend:v1.0 ./backend
          docker build -t dehkai/voxia-frontend:v1.0 ./frontend
          docker build -t dehkai/voxia-rasa:v1.0 ./rasa/app
          docker build -t dehkai/voxia-action-server:v1.0 -f ./rasa/app/Dockerfile.action ./rasa/app
          

      - name: Push Docker images
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push dehkai/voxia-backend:v1.0
          docker push dehkai/voxia-frontend:v1.0
          docker push dehkai/voxia-rasa:v1.0
          docker push dehkai/voxia-action-server:v1.0

