name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file from secrets
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > ./backend/.env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> ./backend/.env
          echo "MONGODB_ATLAS_URI=${{ secrets.MONGODB_ATLAS_URI }}" >> ./.env
          echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" >> ./.env

      - name: Build Backend Docker image
        run: |
          docker buildx build --platform linux/amd64 -t dehkai/voxia-backend:v1.0 ./backend

      - name: Build Frontend Docker image
        run: |
          docker buildx build --platform linux/amd64 -t dehkai/voxia-frontend:v1.0 ./frontend

      - name: Build Rasa Docker image
        run: |
          docker buildx build --platform linux/amd64 -t dehkai/rasa_custom:v1.0 ./rasa/app

      - name: Push Backend Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push dehkai/voxia-backend:v1.0

      - name: Push Frontend Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push dehkai/voxia-frontend:v1.0

      - name: Push Rasa Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push dehkai/rasa_custom:v1.0
