name: Build and Deploy Docker

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  pull_request:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file from secrets
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > ./backend/.env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> ./backend/.env
          # Add more environment variables as needed
          echo "ANOTHER_ENV_VAR=${{ secrets.ANOTHER_ENV_VAR }}" >> ./backend/.env

      - name: Build Docker images
        run: |
          docker build -t dehkai/voxia-backend:v1.0 ./backend
          docker build -t dehkai/voxia-frontend:v1.0 ./frontend

      - name: Run Docker Compose
        run: docker-compose up -d --build

      - name: Wait for services to be healthy
        run: |
          sleep 15  # Wait for the services to start up
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:5000/health  # Change this endpoint to your backend health check
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:3000/health  # Change this endpoint to your frontend health check

      - name: Run tests
        run: |
          docker exec -it backend npm test  # Modify this command as necessary to run your tests
          docker exec -it frontend npm test  # Modify this command as necessary to run your tests

      - name: Push Docker images
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push dehkai/voxia-backend:v1.0
          docker push dehkai/voxia-frontend:v1.0
